dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
language: groovy
sudo: true
jdk:
- openjdk8
branches:
  only:
  - develop
  - master
  - "/release.*/"
env:
  global:
  - RABBIT_USERNAME: guest
  - RABBIT_PASSWORD: guest
  - RABBIT_HOST: localhost
  - RABBIT_EXCHANGE: askme_dev
  - secure: f+dr+18nFnYFZk7nS5iYqaRFQP4fQXwhu6gyFzZHXSD3d2vyQ+H3sfEda9c/LlipiDvrHCMrqLR6EUIa26wR1NHNFD6A4/Zi9UfpSa/DMQaSc1m3NNTY9StXPOF4ui90UhUShyHOCdIRI42fC3lQvrOXmXmIHZqGV79hx5+p/VrhetauuXAKsHxlQ//fgQY7chOgXHbrS8wmrYwXBmGMedRWoc/WP7Rb48VsW9YzO5QExWmp2QCexjPpaB3hMVH/V4zaTmpxrnT20o0TPLrDTB3uaPFIE+Qu89lbOPYAb8Sf8dFuN+Zn5SHwtaEl1lTfuuqWWpWPV9Z0f3U0/3mNnOBjAQj11Bfn/cb5T/EvHPqEbtSsXmh7hSFULynjBCAcqaBVBWiSdQNY/irTICWQUS9gEjZJCNiSRmKGCc4XZ1v7FjmnmFtaRLbXeR+x/ZtifUsWm6lDhhUC2QN1YWOMmHhWOIHmQU/aJ8FNyY0VsYaTLAdjTwgjjXql2IoHMaOPuhgeWgOwRS0NTS/iHTJ8e126XrSSZgDRKRcAYrJ25AncI1snd5WJ2AqlfznajzRBBhvkndoJRJQ0lP3FuzNkFFWEwmnE0LvxEq2cz4PUkm+bikLar9AXYbRz2NSpWq/mDu/EsvK8wBVY9fs3lFOqMZeoKFYF/ZoxosfPC2gsv44=
  - secure: dgncDh6LQPl9I4oaRI59/J+vp0fBjdgjK4+lztLE8mFYzflKWjdLGAmR2y16g1dwcJ5NFtqpl2S6Lt+nKcxTJR+0y3osKnTC1KWfnOE06Q37sHFCYGUk5F+KiCGSVGk1ZGDGun7gPRYhgPX9dIsKq8sh/crlhz9qEI7zWMzTILPZqjWY4GqYflmFM/INlaOwvKplpd8W9d7EolEjPfz3L5YED3NGbdNDEvkHoY1d5MxL2CDpFC6jAxpmzCrvxzQ7bkKQEHOJ1DuMe7/wHH0xP4CcN2ZPkfeQ1LLnwOchQ3iCazd1D1A4rjAtYygD3pgEUNXri4SiRHspNW/ipPIdI/tA0FF0SMstUCbTqhqbf4HngEJbDOUYeKzktUMDCLr+0PKpkBH7N8vLwETxWh16vFO2UAKoCklyEEaEAgAt5dsLio9oICwO7+2pwNBuBSz9JpIjgp2aA+IxzgWf9brAyMzo0EAQbEzFlCTz6NUWe92FlNY8fi0HwIlZuPyzC4ucO/IbUoQqBgeryCelr0EnjlcWkXGf91u+HB11Ez8ObZd2lzZ8xlW+ctZLFJVuyyZenABx4YMJE1Ulm2foIXxsLArFUWES4G6JQ+VYOMk62MzV6cGwmO3PgYP9fU42tmI/RlmA1reiPDizIFcmwgCVVu5YY12kztGdpyZWmNpKyrU=
  - secure: pYEXv9tmZbLxHfbcMwAVO2pd+/le5P43O9iuHqvdYgR3d6EfO86gwdWyGAk/GuzF8JRtOoPdTvGG6upUnxk63Abn4xm5bhJqMVuaG9l4wSW3fv561rjiufZw3v74KlukSjMDNwAg7938hrXPETdB8T4wC43cQR/2zFBrquln6XEDn0ERpVLzQ7itzlM/+KJSN63Vs+PYD8rPtnr3rCwncelIUSVdFK20/tbRYzpph1o211ZKtXTCSXVfXXhlMWKH7lv5/uhqIO9U/5hxZ1uRvfs8z7Jw+bIN57Atxq3+w7A96MBUektAr2YQqpiBLbN/vcY+yMA6jyVJ9WKO+A4QhUEiQKc3bM4VpYWzzjd7tr0cmd6u/DOg+4k57bFqL1uWGGsmAYBv7sHfH8oOl5B0+H09+NgJARbTSKUEIUuFcASABvar5MTM8v5xxX0vvEpHUAuIby/FOsjA4LPQnAyX1lsj2VFf2bAUJ4nTVAKsGWlLNYt8/r5D7IFwqIncCTBOOABFU4RifHu0a0JXHgykMZYGmHF8vA/iO3alvD1Xb5b3gl9YbrQ6Gq/GOx3waVpuiOo4yZFHXrfAe8XcDnK74GHRlTGVdl2TRjI5y4u2ZlYnZ7mQrZyXlYNqJ2vbMuX31er5PaCawrzy25Ko0TwYqI9IP0cfdLt7sZAUhvWw03Q=
  - secure: jt+cCtYlEVkZAxYdBvjQ+m3I0sY0PFvm4BOqB8EZUDGulm/r5X/kLOCx1KGSD+q2ChU7HmuityPnrNg4zGiPbN301xR/6vOh2dl7kx2rqQs1uU1oFNqsYdezw4KZYDNFGhcclzYrIn3cjJN0ZUG6wsKyqNwKL+LgUrAr8fDlScxRGvkXESNmc01pD0iRhuH4JZDnDNUwmI3/v5qKVVCvwbcIk4UXk4QenLDRUDzA/8g6DOt1d0s+Y1aeujVbNSYIILI+6y9JqLx0x33xc0mXO5/x0kkYwUDl16lJY1zaZU3FbnTrZ/gvCbBK83gml13OITaDlnq1Cix1PZQIOfl7OTX6l1ECS4WXEmyLS+lSRq39HsbRM8CpOuYfJy5Autoj+AXqtjQy3ONH7Y869C2RZ9l6znT6WjQC/GFDPpbBFVYOgB8wDxNXsp7522Q4JIGYdiAMMlIg9dlNEdBLhsZDO0mcC2wpRhvOGrkksVM7r04Af0EWh5cnJQI7r1AOCUzRop3Do73l5yA3N2Hm+IKtcMR1vyCpQJPI034k/F6toz0l1co2X2B1UNhSgKpiNL8ArZ4EAvyBO68E8pG23u6CAVpTF00rY3fsxJQXQngePq3NRbLkklfpXG2TMOQjDgAYusaLeBVoHY+HfVMv2RIsVc3vftytsbqsTWNesVEgBn0=
  - secure: Jz39KEUDla6J3wo5jQbQC+p4HXz086XGwRG0mC5RvPfUJDQ8BNwZEUoHqu1Uo1eiB/CmwoOChcSCdB0WEr63NlY2568gGmhmbrmWykg5hps8TEKTG+aiav8gXul0EH07zwieltY+mQI3djSdiBw44gz+0p0dOCMKTDYoJEJ9BfpAjTUZBxlPZ3dbdZN+0fWJStT5jmU6BtpB+6fJ26/UktoEKQRQiUavzIJxuhMXTB/YadNcb4kAb4ZPZf2nNbM3yF1ieIYZzYcjpiLB7omxaZf3E7pBZFnaDG3gRaBtSNVzDjQ0W/v2szT98aVkIQ2QDQW2K4houuRYDHPogdXoIBOG7uszUghEiXOwpfvZxf8GTCMMBR65Xzk2/z1vOxnjBnsAwilXIpHfK+CqZtlQ3HP+VP+XspMd/5xGNMne8cs3mkLGhqgCL9UFEZNIhLEl/Z0rGZU1ESfNJ1HAsZmtEdCiAdpqn8iQ9D/FIf2/KHaZ8ge/IWEljQHS/P/ZCklrByla9piu0/T5G/US8frjkFMRo2x5bkBk9ixFYsq708hzL2sY46veexNk0T2hpEJcO51QdYpw5fA9pAdwsGNy0XgQIlkb94ypL8HN4Qw3nURNoKJtLVgFVidQ4dAxgmrjRI1kbAdPs1RetkIlEWz+ph6cRicbXkvAMWSk1cleYdc=
  - secure: Ng+3tulI9ik2Muvv5G73ClA3X2K/XAKmuUSrl12U5IaoFFmgv1c9up8ejzybVokm8EATqw463vuP5hAMZWLBxGvgLzwqm00p+1qqI3ufU2zA8I85Oi5oMfJRGWVSz5odasv/pmEp7a31EK4HSj1/LKqjCPJAvICZ4tDFcvFiZvPk7atbz+kyfozMTXYhdRvLw8qXCknEmrwsrcNpFmetoplzVmaKSuMAbyfBl9N5VPyNkd47k0hIuGVyvnXKfV5ZNO3dlBe8aqzEIeNN0oc6heOelkF9JaWDC1l3JLM8GdhVPg0l2Fksw2E6lzHsiZ1aTklLv7riB4MiMDEnWh5IINNTYaWP7yuerszHH/2OkFJh5c1pJzZYfW5dZpV8UC6V8fiONhp0gpo5GCH6Ii00Ye1yais7FapyRyAxV9PFPCsNLWlu2uifBfRdQTGQCRhNie6TtLf9CBfHvWzk9fMUu7cMj2fPauFUOITAQvlgDHT4npz/GVSlNjn+MJo++4S7JEYZwoF/gIeP9chn1prTf8qKh5GOVy7CxngHreKhJW9clp7KTT6KIbd1RcRyXfE3fhXPpcppY1KIVOwzrddiYPn4KnSmrb8Twlw/ux9YJ7cYOWCNv23xJSMdVZ55qYZ9SlOr4NsAahqjbOcheQgUV2uXS+mHPBGmIaav9YOPiPI=
stages:
- name: Unit Tests
  if: branch = develop
- name: Staging
  if: branch =~ ^release
- name: Master
  if: branch = master
jobs:
  include:
  - stage: Unit Tests
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pdevelop -B -V install
    script: mvn --settings settings.xml -Pdevelop clean test
  - stage: Staging
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pstaging -B -V install
    script: mvn --settings settings.xml -Dmaven.javadoc.skip=true -Pstaging -B -V
      clean test
    after_success: chmod +x deploy.sh && ./deploy.sh
  - stage: Master
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -B -V install
    script: mvn --settings settings.xml clean test
