language: groovy
branches:
  only:
    - develop
    - master
    - "/release.*/"
env:
  global:
stages:
  - name: Unit Tests
    if: branch = develop
  - name: Staging
    if: branch =~ ^release
  - name: Master
    if: branch = master
jobs:
  include:
    - stage: Unit Tests
      install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
        -Pdevelop -B -V install
      script: mvn --settings settings.xml -Pdevelop clean test
    - stage: Staging
      before-install: chmod +x ./deploy.sh
      install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
        -Pstaging -B -V install
      script: mvn --settings settings.xml -Dmaven.javadoc.skip=true -Pstaging -B -V
        clean test
      after_success: ./deploy.sh
    - stage: Master
      install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
        -B -V install
      script: mvn --settings settings.xml clean test
